# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Posts by categories
    url: 'categories/'
    weight: 20
  - name: Posts by tags
    url: 'tags/'
    weight: 20
  - name: About
    url: 'about/'
    weight: 30
  - name: Subscribe
    url: 'https://ncachanosky.us20.list-manage.com/subscribe/post?u=0e9db4b29e934f6280da794bb&amp;id=f4b6c0baaf'
    weight: 40
  